### ISSUE TITLE
Is `__Nonexhaustive` needed for `HashAlg` enum?

### ISSUE THREAD

**Issue by qarmin** [cybergeek94/img_hash#50]
In my app I use `HashAlg` enum and I must handle `__Nonexhaustive` which is completely not needed for me.

https://github.com/abonander/img_hash/blob/260b9799f7095f090a3a2b04a1cfacd9b24b24f7/src/alg/mod.rs#L138

**Comment by abonander** [comment]
This is the old way of signaling that an enum should not be exhaustively matched, before `#[non_exhaustive]` was added.

Instead of matching on `__Nonexhaustive`, just make sure to have a wildcard (`_`) pattern.
