### ISSUE TITLE
Not compiling with latest version of PistonDevelopers/image and Rust

### ISSUE THREAD

**Issue by forgemo** [cybergeek94/img_hash#6]
I tried to make it compile again and succeeded somehow.

You can find my  changes here: https://github.com/forgemo/img_hash

I, however, failed to keep the image parameter of `square_resize_and_gray` generic.

I had to change

`fn square_resize_and_gray<Img: GenericImage>(img: &Img, size: u32) -> GrayImage`

to 

`fn square_resize_and_gray(img: &RgbImage, size: u32) -> GrayImage`

and did some further modifications following this change.

It seems that my understanding of Rust's generic type-system is not good enough to make it work in a generic manner. Maybe someone could review my changes helping me to make it generic again.

**Comment by cybergeek94** [comment]
Thank you for bringing this to my attention. I'm working on some ideas of my own that should keep `ImageHash::hash` generic without being too complex. Stay tuned.
